extends SceneTree
## Shots to kill, printed as a table and asserted.
##
##     tools/balance_check.sh
##
## WHY A TOOL AND NOT A GUT TEST. CLAUDE.md asks for a GUT test on any system
## with a numeric threshold, and this is the most numeric system in the project.
## GUT is not vendored — tools/lint.sh skips all three existing suites with
## "GUT not vendored" — so a test written there would not run, and a threshold
## nobody runs is a threshold nobody has.
##
## WHAT IT GUARDS. "Machines kill small aliens in one or two shots" is a
## statement about the RATIO of two numbers that live in different files:
## weapon damage in data/gameplay/machines.tres (generated by
## tools/build_machine_data.gd) and hostile HP in data/waves/biodome_01.tres.
## Either can be edited on its own, by hand or by re-running the generator,
## and nothing before this noticed when they drifted apart. They had: a small
## took between three and eight shots from the common guns.
##
## AND IT GUARDS THE OTHER DIRECTION TOO. Smalls dropping to a fifth of their
## HP must not make the nests and roamers trivial — those read their HP from
## hive.tres and hostile_hp() never sees them, but the point of a tier is that
## it reads as a tier, so the ratio is asserted rather than assumed.

## The window "one or two shots" is checked against, for the guns a player
## meets early. Weapons that already one-shot a small are not interesting here;
## what matters is that nothing common needs three.
const MAX_SHOTS := 2
## Beams have no shots, so they are held to a time instead.
const MAX_BEAM_S := 2.5


func _initialize() -> void:
	var waves: WaveTable = load("res://data/waves/biodome_01.tres")
	var hive: HiveConfig = load("res://data/gameplay/hive.tres")
	var ok := true

	# THE WORST CASE, not the average. hostile_hp() grows with intensity and
	# with elapsed time, so a small is toughest at the end of a long dig — and
	# that is the one that has to still die in two shots, or the claim only
	# holds for the first thirty seconds of a mission.
	var hp_worst: float = waves.hp_base \
		+ waves.hp_per_wave * 1.6 * (1.0 + 26.0 / 60.0)
	print("SENTINEL — balance\n")
	print("small alien HP: %.1f fresh, %.1f worst case (intensity 1.6, 26 s in)"
		% [waves.hp_base + waves.hp_per_wave, hp_worst])
	print("nest %.0f, roamer %.0f\n" % [hive.plant_hp, hive.roamer_hp])

	print("%-16s %-16s %7s %9s %7s %8s"
		% ["machine", "weapon", "damage", "cooldown", "shots", "TTK"])
	var worst_shots := 0
	var worst_name := ""
	var one_shot := 0
	var guns := 0
	var dir := DirAccess.open("res://data/gameplay/build_options")
	var names := dir.get_files()
	names.sort()
	for f in names:
		if not f.ends_with(".tres"):
			continue
		var opt: BuildOption = load("res://data/gameplay/build_options/" + f)
		if opt == null or opt.loadout == null:
			continue
		for part in opt.loadout.fitted:
			var p: MachinePart = part
			if p == null or p.damage <= 0.0:
				continue
			guns += 1
			# A beam does `damage` per SECOND once it has ramped, so "shots" is
			# not the right unit for it; it is scored on time below instead.
			var beam: bool = p.family == MachinePart.Family.BEAM
			if beam:
				var secs: float = hp_worst / maxf(p.damage, 0.001)
				print("%-16s %-16s %6.0f/s %9s %7s %7.2fs"
					% [opt.id, p.id, p.damage, "—", "beam", secs])
				if secs > MAX_BEAM_S:
					push_error("%s needs %.2f s on a small, over the %.1f s bar"
						% [p.id, secs, MAX_BEAM_S])
					ok = false
				continue
			var shots := int(ceil(hp_worst / p.damage))
			var ttk: float = float(shots - 1) * p.cooldown_s
			print("%-16s %-16s %7.0f %8.2fs %7d %7.2fs"
				% [opt.id, p.id, p.damage, p.cooldown_s, shots, ttk])
			if shots <= 1:
				one_shot += 1
			if shots > worst_shots:
				worst_shots = shots
				worst_name = "%s/%s" % [opt.id, p.id]
	print("")

	if guns == 0:
		push_error("no weapons found — the catalogue moved and this check is "
			+ "now asserting nothing")
		quit(1)
		return

	if not _ok("every gun kills a small in %d shots or fewer" % MAX_SHOTS,
			worst_shots <= MAX_SHOTS,
			"worst is %s at %d" % [worst_name, worst_shots]):
		ok = false

	# NOT SO CHEAP THEY STOP COUNTING. One shot from everything means the
	# player never chooses a gun, which is the same collapse as everything
	# needing eight.
	var frac := float(one_shot) / maxf(float(guns), 1.0)
	if not _ok("but not every gun one-shots them", frac < 0.85,
			"%d of %d do (%.0f%%)" % [one_shot, guns, frac * 100.0]):
		ok = false

	# THE TIERS STILL READ AS TIERS.
	if not _ok("a nest is worth several smalls", hive.plant_hp >= hp_worst * 4.0,
			"%.0f against %.1f (%.1fx)"
			% [hive.plant_hp, hp_worst, hive.plant_hp / hp_worst]):
		ok = false
	if not _ok("and a roamer worth several nests",
			hive.roamer_hp >= hive.plant_hp * 1.8,
			"%.0f against %.0f (%.1fx)"
			% [hive.roamer_hp, hive.plant_hp, hive.roamer_hp / hive.plant_hp]):
		ok = false

	# THE WAVE ACTUALLY ARRIVES. At interval_s 45 the second group landed at
	# 39.4 s, past the end of a 26 s dig, so a "wave" was one group however
	# large count_base was. The count is worth nothing without the cadence.
	var groups := int(floor(26.0 / waves.interval_s)) + 1
	var per_group: float = (waves.count_base + waves.count_per_wave) * 1.6
	if not _ok("a dig sees more than one group", groups >= 2,
			"%d groups of ~%.0f in 26 s" % [groups, per_group]):
		ok = false

	# AND EVERY ONE OF THEM IS DRAWN. 40 skinned + 192 instanced is the hard
	# ceiling in _make_instancers; past it an alien is simulated, walks and
	# bites while being invisible, which is the least fair failure in the game.
	var peak: float = per_group * float(groups)
	if not _ok("the peak is inside the 232 the renderer can draw",
			peak <= 232.0, "peak ~%.0f" % peak):
		ok = false

	print("\nBALANCE: %s" % ("OK" if ok else "FAILED"))
	quit(0 if ok else 1)


func _ok(what: String, pass_: bool, detail: String) -> bool:
	print("  %s  %-46s %s" % ["PASS" if pass_ else "FAIL", what, detail])
	return pass_
